### ISSUE TITLE
 Narrative Service: Different behaviour in frontend with the same (object) disease

### ISSUE THREAD

**Issue by ir0ntr0nik** [HermannKroll/NarrativeIntelligence#131]
DrugOverview: Simvastatin -> Indications -> "Absence of Tibia" as a result (image 2). The link redirects to narrative.pubpharm.de/?query=Simvastatin+treats+"Absence+of+Tibia"&data_source=PubMed .

Neather local nor on the narrative service website the drug "Absence of Tibia" is known (image 1).

![grafik](https://user-images.githubusercontent.com/20024791/176991814-769f5ebe-f44e-4601-810a-33f27744fdec.png)
![grafik](https://user-images.githubusercontent.com/20024791/176991827-50ecacfb-9476-44f0-ac65-48a95212e860.png)

**Comment by HermannKroll** [comment]
This has now been fixed.
