### ISSUE TITLE
Narrative Service: additional PubChem information

### ISSUE THREAD

**Issue by ir0ntr0nik** [HermannKroll/NarrativeIntelligence#189]
Is there a way to retrieve the PubChem id from the ChemblApi Drug-Request. To be precise: does the data contain the id?

If not: is there any other way to retrieve this information via the API?

**Comment by HermannKroll** [comment]
Experts need to specify a set of relevant properties:
https://pubchem.ncbi.nlm.nih.gov/compound/54454

**Comment by HermannKroll** [comment]
We added a link to PubChem in Drug Overviews. So this issue can be closed now.
