### ISSUE TITLE
NarrativeService: Sorting options result list

### ISSUE THREAD

**Issue by pubpharm** [HermannKroll/NarrativeIntelligence#199]
Comment at Roadshow Greifswald: More Sorting options for the result list (like in PubPharm)

**Comment by HermannKroll** [comment]
Build another checkbox filter with "Systematic Review" in our filter box. Implement that filter as a title search:

"systemat+review"

https://narrative.pubpharm.de/?query=Metformin+treats+%22Diabetes+Mellitus%22&data_source=PubMed&title_filter=systemat+review

**Comment by HermannKroll** [comment]
Should be resetted if a new search is conducted

**Comment by HermannKroll** [comment]
Solved.
