### ISSUE TITLE
DrugOverviews: Drug-Target-Disesase Network

### ISSUE THREAD

**Issue by pubpharm** [HermannKroll/NarrativeIntelligence#202]
More information on functions is directly required (e.g., hover tipps) --> TBD in the team

Feedback from the Roadshow Greifswald

**Comment by HermannKroll** [comment]
Integrate the following options:
- Hover over an edge in the network: "Search in Narrative Service"
- Hover over an interaction in one of the lists  (over the number of publications): "Search in Narrative Service"
- Hover over a clinical trial phase: "Search in ChEMBL"
- add the interaction types in the entity type selection box in the network view: red = associated, green = treats and blue = interacts: Associated Drug, Disease Therapy, Target Interaction
