### ISSUE TITLE
SSL Security Problem

### ISSUE THREAD

**Issue by HermannKroll** [HermannKroll/NarrativeIntelligence#211]
Why is the following link insecure:
 https://www.narrative.pubpharm.de/document/?document_id=35085707&data_source=PubMed

But 
https://narrative.pubpharm.de/document/?document_id=35085707&data_source=PubMed

is secure? Seems to be a SSL configuration problem.

**Comment by ir0ntr0nik** [comment]
As far as I can see, the corresponding Django [config](https://github.com/HermannKroll/NarrativeIntelligence/blob/fa11a1f93a55c5906df514ddfd2409b71609d4a9/src/narraint/frontend/frontend/settings/prod.py) already contains both URLs as `ALLOWED_HOSTS`.

The first link results in an error with the description `SSL_ERROR_BAD_CERT_DOMAIN`.

I found a similar problem: https://stackoverflow.com/questions/51749452/django-url-with-www-is-not-safe
The solution is to generate a certificate that is also valid for the subdomain `www.narrative.pubpharm.de`.

**Comment by HermannKroll** [comment]
I have to generate a new certificate.

**Comment by HermannKroll** [comment]
Solution was to redirect from www.narrative.pubpharm.de to narrative.pubpharm.de

**Comment by HermannKroll** [comment]
Should be obsolete by now.
