### ISSUE TITLE
Narrative Service: Why do we have trackers?

### ISSUE THREAD

**Issue by HermannKroll** [HermannKroll/NarrativeIntelligence#214]
My Apple Safari browser claims that we use two trackers on our website. Why?

<img width="1167" alt="image" src="https://github.com/HermannKroll/NarrativeIntelligence/assets/6368738/6de89ac6-5851-497b-8740-9a8e0f55ebd3">

**Comment by ir0ntr0nik** [comment]
For now, the following dependencies are delivered via the service:

name | type | / | stats | logs | help | document | drug_overview | long_covid | covid19 | mecfs
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
bootstrap.min.css | jsdelivr.net | + |   |   | + | + | + | + | + | +
bootstrap.bundle.min.js | jsdelivr.net | + |   |   | + | + | + | + | + | +
Chart.min.js | cloudflare.com | + |   | + | + | + | + | + | + | +
jquery-3.7.0.min.js | cloudflare.com | + |   |   |   |   |   |   |   |  
mark.min.js | cloudflare.com | + |   |   |   | + | + | + | + | +
async.min.js | cloudflare.com | + |   |   |   | + | + | + | + | +

**Comment by HermannKroll** [comment]
Solved.
