### ISSUE TITLE
Check for other extraction options

### ISSUE THREAD

**Issue by m-thang** [HermannKroll/NarrativeIntelligence#221]
Review the contents of the following resources: doi.org/10.1145/3560815 and doi.org/10.18653/v1/2022.acl-long.556.

Subsequently, prepare a presentation consisting of 5 to 10 slides. This presentation should address the level of effort required and the essential steps needed for implementation.

**Comment by HermannKroll** [comment]
Text from issue #167 which is now closed:
http://narrative.pubpharm.de/drug_overview/?drug=Lumefantrine

die Darreichungsformen stimmen teilweise nicht: z.B Spray und i.m. Injection
bei den Sprays ist der Sprühprozess Teil der Herstellung, aber nicht die Darreichungsform
bei der i.m. Injektion wurde Lumefantrine oral eingenommen, die i.m. Injektion war gegen die Nebenwirkungen

**Comment by HermannKroll** [comment]
We have collected user feedback. Could we use active learning?

**Comment by m-thang** [comment]
[Prompting.pdf](https://github.com/HermannKroll/NarrativeIntelligence/files/12926646/Prompting.pdf)

**Comment by HermannKroll** [comment]
We did a comprehensive evaluation for JCDL2024 (A Library Perspective on Supervised Text Processing). For more information, please have a look at the paper.
