### ISSUE TITLE
Additional NarrativeService search method: keyword query

### ISSUE THREAD

**Issue by ir0ntr0nik** [HermannKroll/NarrativeIntelligence#222]
Add the functionality to the search using keywords and a resulting graph selection. The main idea is that users can switch between the current subject-predicate-object input search and a new keyword-graph search like in `/keyword_search/`.

1. add the required frontend input HTML
2. implement the frontend business logic (toggle, submit, error handling, etc.)
3. implement the backend path and, for now, a static but working example

**Comment by HermannKroll** [comment]
Idea:
- Basic schema graph of basic entity types (count support for edges between each entity type)
- Also introduce negative edges, i.e., how often two entities are in the same document but do not have a direct connection (statement extraction) of type X (e.g, connected via associated but not via TREATS = X)


Three strategies:
- specific relations + connected graph
- associated relations + connected graph
- specific relations + not fully connected graph

Metformin treats Diabetes  +      Rat
     8k doc ids                                 2M doc ids
                              Intersection

**Comment by HermannKroll** [comment]
4. Die Richtung der Pfeile kann aktuell missleading sein. Also die Richtungen passen nicht zwingend. Hat was mit internen Umschreiberegeln zu tun. Ungerichtete Verbindungen nehmen? Ohne Pfeilspitzen?

**Comment by HermannKroll** [comment]
Approved by experts.

**Comment by HermannKroll** [comment]
But the last selected query needs to be shown in the query builder.

**Comment by HermannKroll** [comment]
Documentation must be updated.
