### ISSUE TITLE
Narrative Service: Keyword Search improvements

### ISSUE THREAD

**Issue by HermannKroll** [HermannKroll/NarrativeIntelligence#231]
1. Safari seems to cut of entered concepts. I assume that our rule skip the last two characters does not work, because Safari is setting a different input than Firefox/Chrome.

Firefox and Chrome work fine on Mac. Just Safari has a different behavior.

Metformin is shrinked to Metformi => This will cause a different result in the end. 
<img width="545" alt="image" src="https://github.com/HermannKroll/NarrativeIntelligence/assets/6368738/2878b3df-de6f-41e2-9495-2f0cf0954fa1">

2. Sometimes the tooltip is shown permanently. If you hover over a generated graph pattern, then the tooltip remains open some times (Firefox, Windows and Mac -> Seems to be a general problem) .

This also applies to the tooltip for concept explanations. In the same rework, a caching could be implemented to that concept explanations are only queried if the subject/object is changed.

![image](https://github.com/HermannKroll/NarrativeIntelligence/assets/6368738/8febb0ac-f499-4ee7-8fdb-903a3cddf12f)

4. We need a better help/tooltip/assistance. It was unclear for our users that they have to press enter after each concept. I am not sure how to do so. Suggestions? 

5. If you select a graph pattern, then the query is executed. However, due to the refresh the input field for keyword search is then cleared. Also the suggested patterns are removed. This should not be the default behavior. The graph patterns should still be shown. 
![image](https://github.com/HermannKroll/NarrativeIntelligence/assets/6368738/0738deeb-7b98-44a0-8709-f6677a351eb2)

6. "List out of range error" shown for this search: -> Seems to be a backend problem.

![image](https://github.com/HermannKroll/NarrativeIntelligence/assets/6368738/a898bedf-2f38-479b-aec4-b315b16631fe)

7. The selected pattern is not highlighted with the red border. 
<img width="1588" alt="image" src="https://github.com/HermannKroll/NarrativeIntelligence/assets/6368738/d381c1d3-b294-4b23-8302-4386fa8591ee">

8. Duplicated queries are generated. I assume that this is because of one pattern contains (s, p, o) and the other flips object and subject, i.e., (o, p, s). 
<img width="836" alt="Duplicated patterns" src="https://github.com/HermannKroll/NarrativeIntelligence/assets/6368738/890b9ac6-49da-4c8d-8a96-f4d52d59365d">

**Comment by HermannKroll** [comment]
1. Solved (replace \n if and only remove one character. Seems to work fine now).
3. Improved but not solved.
4. Deactivated keyword refresh for now

**Comment by HermannKroll** [comment]
6 was a crucial bug in the entity translation. The Lab Method entity was not assigned correctly in the translation step. This could also affect the search behaviour of the narrative service as no LabMethods were searched at the moment.

**Comment by HermannKroll** [comment]
8 solved.

**Comment by ir0ntr0nik** [comment]
Solved.
