### ISSUE TITLE
Narrative Service: Low memory mode for inverse index is now broken

### ISSUE THREAD

**Issue by HermannKroll** [HermannKroll/NarrativeIntelligence#273]
The low memory mode for inverse index creation does not work anymore because gene ids need to be translated to symbols. In other words, we cannot sort the tag/predication table in advance as other gene ids may map to the same symbol which may lead into invalid indexes.

**Comment by ir0ntr0nik** [comment]
Applies only to Tag-table.

**Comment by HermannKroll** [comment]
We will optimize the index creation scripts by relying on the last db update date. Then we query all documents that are newer than this data und process them in the index creation.
