### ISSUE TITLE
Narrative Service: Old MeSH Supplement Concepts

### ISSUE THREAD

**Issue by HermannKroll** [HermannKroll/NarrativeIntelligence#275]
The drug overview can show associations/treats relationships to MeSH Supplement concepts that are not translated, see the image. The reason is that this supplement is not present anymore in the MeSH Supplement DB. Maybe we should create a script to delete those supplements from our DB if they are not present in the official MeSH Supplement.

Design a script that receives all MESH things from DB (Tag Table, ent_id like 'MESH:%'). Check for every id whether it is present in MeSH DB or Supplement. Then show the missing concepts and ask the user whether the missing concepts should be deleted (and have a -f --force argument option). 

Data must be deleted from Tag and Predication Table. Script should be added in Narrative Annnotation. Maybe in cleaning.

![Unknown-3](https://github.com/HermannKroll/NarrativeIntelligence/assets/6368738/536f72d6-a2f6-4ba5-902c-7a77101e5e37)

**Comment by ir0ntr0nik** [comment]
see NarrativeAnnotation [commit](https://github.com/HermannKroll/NarrativeAnnotation/commit/7a557d5bbb272dcea82dd515ea86089d2ff5cd70): `#275 add a script to delete old mesh terms from tag and predication table`

**Comment by HermannKroll** [comment]
See NarrativeAnnotation [commit](https://github.com/HermannKroll/NarrativeAnnotation/commit/22fe2b7bb169c9a7dec5f06e376b58875abb3f37): make script faster and fix error
